[project]
name = "op-schema"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "chupper87", email = "daniel_yanez87@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "annotated-types>=0.7.0",
    "anyio>=4.10.0",
    "bcrypt>=4.3.0",
    "certifi>=2025.8.3",
    "click>=8.2.1",
    "colorama>=0.4.6",
    "dnspython>=2.7.0",
    "email-validator>=2.3.0",
    "fastapi>=0.116.1",
    "fastapi-cli>=0.0.10",
    "fastapi-cloud-cli>=0.1.5",
    "fastapi-mail>=1.5.0",
    "greenlet>=3.2.4",
    "h11>=0.16.0",
    "httpcore>=1.0.9",
    "httptools>=0.6.4",
    "httpx>=0.28.1",
    "idna>=3.10",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "mako>=1.3.10",
    "markdown-it-py>=4.0.0",
    "markupsafe>=3.0.2",
    "mdurl>=0.1.2",
    "packaging>=25.0",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.7",
    "pydantic-core>=2.33.2",
    "pydantic-settings>=2.10.1",
    "pygments>=2.19.2",
    "pyjwt>=2.10.1",
    "pytest-cov>=7.0.0",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "pyyaml>=6.0.2",
    "rich>=14.1.0",
    "rich-toolkit>=0.15.1",
    "sentry-sdk>=2.37.0",
    "shellingham>=1.5.4",
    "sniffio>=1.3.1",
    "sqlalchemy>=2.0.43",
    "starlette>=0.47.3",
    "typer>=0.17.4",
    "typing-extensions>=4.15.0",
    "typing-inspection>=0.4.1",
    "urllib3>=2.5.0",
    "uv>=0.8.15",
    "uvicorn>=0.35.0",
    "watchfiles>=1.1.0",
    "websockets>=15.0.1",
    "win32-setctime>=1.2.0",
]

[project.scripts]
op-schema = "op_schema:main"

[tool.uv]
dev-dependencies = [
    "pytest>=8.4.2",
    "pyright>=1.1.405",
    "ruff>=0.12.12",
    "pre-commit",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
